-- Fugitive is the premier Vim plugin for Git
-- https://github.com/tpope/vim-fugitive
return {
  'tpope/vim-fugitive',
  cmd = {
    'G',
    'Git',
    'Gstatus',
    'Gcd',
    'Glcd',
    'Ggrep',
    'Glgrep',
    'Gclog',
    'GcLog',
    'Gllog',
    'GlLog',
    'Ge',
    'Gedit',
    'Gpedit',
    'Gsplit',
    'Gvsplit',
    'Gtabedit',
    'Gdrop',
    'Gr',
    'Gread',
    'Gdiffsplit',
    'Ghdiffsplit',
    'Gvdiffsplit',
    'Gw',
    'Gwrite',
    'Gwq',
    'GRemove',
    'GUnlink',
    'GDelete',
    'GMove',
    'GRename',
    'GBrowse',
    'Gremove',
    'Gdelete',
    'Gmove',
    'Grename',
    'Gbrowse',
  },
}
